package com.room.backend.data.entity;

import java.io.Serializable;
import java.util.Date;

public class ApartmentsInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartments_info.id
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartments_info.name
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartments_info.state
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartments_info.city
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartments_info.street
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartments_info.zip
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private Integer zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartments_info.lat
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private Float lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartments_info.lng
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private Float lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartments_info.structure
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private String structure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartments_info.create_time
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apartments_info.last_modify
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private Date last_modify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartments_info.id
     *
     * @return the value of apartments_info.id
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartments_info.id
     *
     * @param id the value for apartments_info.id
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartments_info.name
     *
     * @return the value of apartments_info.name
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartments_info.name
     *
     * @param name the value for apartments_info.name
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartments_info.state
     *
     * @return the value of apartments_info.state
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartments_info.state
     *
     * @param state the value for apartments_info.state
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartments_info.city
     *
     * @return the value of apartments_info.city
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartments_info.city
     *
     * @param city the value for apartments_info.city
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartments_info.street
     *
     * @return the value of apartments_info.street
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartments_info.street
     *
     * @param street the value for apartments_info.street
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartments_info.zip
     *
     * @return the value of apartments_info.zip
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public Integer getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartments_info.zip
     *
     * @param zip the value for apartments_info.zip
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setZip(Integer zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartments_info.lat
     *
     * @return the value of apartments_info.lat
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public Float getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartments_info.lat
     *
     * @param lat the value for apartments_info.lat
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartments_info.lng
     *
     * @return the value of apartments_info.lng
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public Float getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartments_info.lng
     *
     * @param lng the value for apartments_info.lng
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setLng(Float lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartments_info.structure
     *
     * @return the value of apartments_info.structure
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public String getStructure() {
        return structure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartments_info.structure
     *
     * @param structure the value for apartments_info.structure
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setStructure(String structure) {
        this.structure = structure == null ? null : structure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartments_info.create_time
     *
     * @return the value of apartments_info.create_time
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartments_info.create_time
     *
     * @param create_time the value for apartments_info.create_time
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apartments_info.last_modify
     *
     * @return the value of apartments_info.last_modify
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public Date getLast_modify() {
        return last_modify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apartments_info.last_modify
     *
     * @param last_modify the value for apartments_info.last_modify
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setLast_modify(Date last_modify) {
        this.last_modify = last_modify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", state=").append(state);
        sb.append(", city=").append(city);
        sb.append(", street=").append(street);
        sb.append(", zip=").append(zip);
        sb.append(", lat=").append(lat);
        sb.append(", lng=").append(lng);
        sb.append(", structure=").append(structure);
        sb.append(", create_time=").append(create_time);
        sb.append(", last_modify=").append(last_modify);
        sb.append("]");
        return sb.toString();
    }
}