package com.room.backend.data._generated.entity;

import java.io.Serializable;

public class Hobby implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hobby.id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hobby.name
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hobby
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hobby.id
     *
     * @return the value of hobby.id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hobby.id
     *
     * @param id the value for hobby.id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hobby.name
     *
     * @return the value of hobby.name
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hobby.name
     *
     * @param name the value for hobby.name
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hobby
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}