package com.room.backend.data._generated.entity;

import java.io.Serializable;
import java.util.Date;

public class UserFavApartment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fav_apartment.u_id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private Integer u_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fav_apartment.a_id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private Integer a_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fav_apartment.create_time
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fav_apartment.last_modify
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private Date last_modify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_fav_apartment
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fav_apartment.u_id
     *
     * @return the value of user_fav_apartment.u_id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public Integer getU_id() {
        return u_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fav_apartment.u_id
     *
     * @param u_id the value for user_fav_apartment.u_id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setU_id(Integer u_id) {
        this.u_id = u_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fav_apartment.a_id
     *
     * @return the value of user_fav_apartment.a_id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public Integer getA_id() {
        return a_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fav_apartment.a_id
     *
     * @param a_id the value for user_fav_apartment.a_id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setA_id(Integer a_id) {
        this.a_id = a_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fav_apartment.create_time
     *
     * @return the value of user_fav_apartment.create_time
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fav_apartment.create_time
     *
     * @param create_time the value for user_fav_apartment.create_time
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fav_apartment.last_modify
     *
     * @return the value of user_fav_apartment.last_modify
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public Date getLast_modify() {
        return last_modify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fav_apartment.last_modify
     *
     * @param last_modify the value for user_fav_apartment.last_modify
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setLast_modify(Date last_modify) {
        this.last_modify = last_modify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_apartment
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", u_id=").append(u_id);
        sb.append(", a_id=").append(a_id);
        sb.append(", create_time=").append(create_time);
        sb.append(", last_modify=").append(last_modify);
        sb.append("]");
        return sb.toString();
    }
}