package com.room.backend.data._generated.entity;

import java.io.Serializable;
import java.util.Date;

public class UsersLogin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_login.id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_login.password_encoded
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private String password_encoded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_login.create_time
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_login.last_modify
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private Date last_modify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_login.role_id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private Integer role_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_login
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_login.id
     *
     * @return the value of users_login.id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_login.id
     *
     * @param id the value for users_login.id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_login.password_encoded
     *
     * @return the value of users_login.password_encoded
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public String getPassword_encoded() {
        return password_encoded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_login.password_encoded
     *
     * @param password_encoded the value for users_login.password_encoded
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setPassword_encoded(String password_encoded) {
        this.password_encoded = password_encoded == null ? null : password_encoded.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_login.create_time
     *
     * @return the value of users_login.create_time
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_login.create_time
     *
     * @param create_time the value for users_login.create_time
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_login.last_modify
     *
     * @return the value of users_login.last_modify
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public Date getLast_modify() {
        return last_modify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_login.last_modify
     *
     * @param last_modify the value for users_login.last_modify
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setLast_modify(Date last_modify) {
        this.last_modify = last_modify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_login.role_id
     *
     * @return the value of users_login.role_id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public Integer getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_login.role_id
     *
     * @param role_id the value for users_login.role_id
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setRole_id(Integer role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_login
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", password_encoded=").append(password_encoded);
        sb.append(", create_time=").append(create_time);
        sb.append(", last_modify=").append(last_modify);
        sb.append(", role_id=").append(role_id);
        sb.append("]");
        return sb.toString();
    }
}