package com.room.backend.data._generated.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UsersPrefExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public UsersPrefExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andU_idIsNull() {
            addCriterion("u_id is null");
            return (Criteria) this;
        }

        public Criteria andU_idIsNotNull() {
            addCriterion("u_id is not null");
            return (Criteria) this;
        }

        public Criteria andU_idEqualTo(Integer value) {
            addCriterion("u_id =", value, "u_id");
            return (Criteria) this;
        }

        public Criteria andU_idNotEqualTo(Integer value) {
            addCriterion("u_id <>", value, "u_id");
            return (Criteria) this;
        }

        public Criteria andU_idGreaterThan(Integer value) {
            addCriterion("u_id >", value, "u_id");
            return (Criteria) this;
        }

        public Criteria andU_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("u_id >=", value, "u_id");
            return (Criteria) this;
        }

        public Criteria andU_idLessThan(Integer value) {
            addCriterion("u_id <", value, "u_id");
            return (Criteria) this;
        }

        public Criteria andU_idLessThanOrEqualTo(Integer value) {
            addCriterion("u_id <=", value, "u_id");
            return (Criteria) this;
        }

        public Criteria andU_idIn(List<Integer> values) {
            addCriterion("u_id in", values, "u_id");
            return (Criteria) this;
        }

        public Criteria andU_idNotIn(List<Integer> values) {
            addCriterion("u_id not in", values, "u_id");
            return (Criteria) this;
        }

        public Criteria andU_idBetween(Integer value1, Integer value2) {
            addCriterion("u_id between", value1, value2, "u_id");
            return (Criteria) this;
        }

        public Criteria andU_idNotBetween(Integer value1, Integer value2) {
            addCriterion("u_id not between", value1, value2, "u_id");
            return (Criteria) this;
        }

        public Criteria andMajorIsNull() {
            addCriterion("major is null");
            return (Criteria) this;
        }

        public Criteria andMajorIsNotNull() {
            addCriterion("major is not null");
            return (Criteria) this;
        }

        public Criteria andMajorEqualTo(String value) {
            addCriterion("major =", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotEqualTo(String value) {
            addCriterion("major <>", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorGreaterThan(String value) {
            addCriterion("major >", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorGreaterThanOrEqualTo(String value) {
            addCriterion("major >=", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLessThan(String value) {
            addCriterion("major <", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLessThanOrEqualTo(String value) {
            addCriterion("major <=", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLike(String value) {
            addCriterion("major like", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotLike(String value) {
            addCriterion("major not like", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorIn(List<String> values) {
            addCriterion("major in", values, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotIn(List<String> values) {
            addCriterion("major not in", values, "major");
            return (Criteria) this;
        }

        public Criteria andMajorBetween(String value1, String value2) {
            addCriterion("major between", value1, value2, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotBetween(String value1, String value2) {
            addCriterion("major not between", value1, value2, "major");
            return (Criteria) this;
        }

        public Criteria andSocial_ratingIsNull() {
            addCriterion("social_rating is null");
            return (Criteria) this;
        }

        public Criteria andSocial_ratingIsNotNull() {
            addCriterion("social_rating is not null");
            return (Criteria) this;
        }

        public Criteria andSocial_ratingEqualTo(Integer value) {
            addCriterion("social_rating =", value, "social_rating");
            return (Criteria) this;
        }

        public Criteria andSocial_ratingNotEqualTo(Integer value) {
            addCriterion("social_rating <>", value, "social_rating");
            return (Criteria) this;
        }

        public Criteria andSocial_ratingGreaterThan(Integer value) {
            addCriterion("social_rating >", value, "social_rating");
            return (Criteria) this;
        }

        public Criteria andSocial_ratingGreaterThanOrEqualTo(Integer value) {
            addCriterion("social_rating >=", value, "social_rating");
            return (Criteria) this;
        }

        public Criteria andSocial_ratingLessThan(Integer value) {
            addCriterion("social_rating <", value, "social_rating");
            return (Criteria) this;
        }

        public Criteria andSocial_ratingLessThanOrEqualTo(Integer value) {
            addCriterion("social_rating <=", value, "social_rating");
            return (Criteria) this;
        }

        public Criteria andSocial_ratingIn(List<Integer> values) {
            addCriterion("social_rating in", values, "social_rating");
            return (Criteria) this;
        }

        public Criteria andSocial_ratingNotIn(List<Integer> values) {
            addCriterion("social_rating not in", values, "social_rating");
            return (Criteria) this;
        }

        public Criteria andSocial_ratingBetween(Integer value1, Integer value2) {
            addCriterion("social_rating between", value1, value2, "social_rating");
            return (Criteria) this;
        }

        public Criteria andSocial_ratingNotBetween(Integer value1, Integer value2) {
            addCriterion("social_rating not between", value1, value2, "social_rating");
            return (Criteria) this;
        }

        public Criteria andPet_ratingIsNull() {
            addCriterion("pet_rating is null");
            return (Criteria) this;
        }

        public Criteria andPet_ratingIsNotNull() {
            addCriterion("pet_rating is not null");
            return (Criteria) this;
        }

        public Criteria andPet_ratingEqualTo(Integer value) {
            addCriterion("pet_rating =", value, "pet_rating");
            return (Criteria) this;
        }

        public Criteria andPet_ratingNotEqualTo(Integer value) {
            addCriterion("pet_rating <>", value, "pet_rating");
            return (Criteria) this;
        }

        public Criteria andPet_ratingGreaterThan(Integer value) {
            addCriterion("pet_rating >", value, "pet_rating");
            return (Criteria) this;
        }

        public Criteria andPet_ratingGreaterThanOrEqualTo(Integer value) {
            addCriterion("pet_rating >=", value, "pet_rating");
            return (Criteria) this;
        }

        public Criteria andPet_ratingLessThan(Integer value) {
            addCriterion("pet_rating <", value, "pet_rating");
            return (Criteria) this;
        }

        public Criteria andPet_ratingLessThanOrEqualTo(Integer value) {
            addCriterion("pet_rating <=", value, "pet_rating");
            return (Criteria) this;
        }

        public Criteria andPet_ratingIn(List<Integer> values) {
            addCriterion("pet_rating in", values, "pet_rating");
            return (Criteria) this;
        }

        public Criteria andPet_ratingNotIn(List<Integer> values) {
            addCriterion("pet_rating not in", values, "pet_rating");
            return (Criteria) this;
        }

        public Criteria andPet_ratingBetween(Integer value1, Integer value2) {
            addCriterion("pet_rating between", value1, value2, "pet_rating");
            return (Criteria) this;
        }

        public Criteria andPet_ratingNotBetween(Integer value1, Integer value2) {
            addCriterion("pet_rating not between", value1, value2, "pet_rating");
            return (Criteria) this;
        }

        public Criteria andCook_ratingIsNull() {
            addCriterion("cook_rating is null");
            return (Criteria) this;
        }

        public Criteria andCook_ratingIsNotNull() {
            addCriterion("cook_rating is not null");
            return (Criteria) this;
        }

        public Criteria andCook_ratingEqualTo(Integer value) {
            addCriterion("cook_rating =", value, "cook_rating");
            return (Criteria) this;
        }

        public Criteria andCook_ratingNotEqualTo(Integer value) {
            addCriterion("cook_rating <>", value, "cook_rating");
            return (Criteria) this;
        }

        public Criteria andCook_ratingGreaterThan(Integer value) {
            addCriterion("cook_rating >", value, "cook_rating");
            return (Criteria) this;
        }

        public Criteria andCook_ratingGreaterThanOrEqualTo(Integer value) {
            addCriterion("cook_rating >=", value, "cook_rating");
            return (Criteria) this;
        }

        public Criteria andCook_ratingLessThan(Integer value) {
            addCriterion("cook_rating <", value, "cook_rating");
            return (Criteria) this;
        }

        public Criteria andCook_ratingLessThanOrEqualTo(Integer value) {
            addCriterion("cook_rating <=", value, "cook_rating");
            return (Criteria) this;
        }

        public Criteria andCook_ratingIn(List<Integer> values) {
            addCriterion("cook_rating in", values, "cook_rating");
            return (Criteria) this;
        }

        public Criteria andCook_ratingNotIn(List<Integer> values) {
            addCriterion("cook_rating not in", values, "cook_rating");
            return (Criteria) this;
        }

        public Criteria andCook_ratingBetween(Integer value1, Integer value2) {
            addCriterion("cook_rating between", value1, value2, "cook_rating");
            return (Criteria) this;
        }

        public Criteria andCook_ratingNotBetween(Integer value1, Integer value2) {
            addCriterion("cook_rating not between", value1, value2, "cook_rating");
            return (Criteria) this;
        }

        public Criteria andNoise_toleranceIsNull() {
            addCriterion("noise_tolerance is null");
            return (Criteria) this;
        }

        public Criteria andNoise_toleranceIsNotNull() {
            addCriterion("noise_tolerance is not null");
            return (Criteria) this;
        }

        public Criteria andNoise_toleranceEqualTo(Integer value) {
            addCriterion("noise_tolerance =", value, "noise_tolerance");
            return (Criteria) this;
        }

        public Criteria andNoise_toleranceNotEqualTo(Integer value) {
            addCriterion("noise_tolerance <>", value, "noise_tolerance");
            return (Criteria) this;
        }

        public Criteria andNoise_toleranceGreaterThan(Integer value) {
            addCriterion("noise_tolerance >", value, "noise_tolerance");
            return (Criteria) this;
        }

        public Criteria andNoise_toleranceGreaterThanOrEqualTo(Integer value) {
            addCriterion("noise_tolerance >=", value, "noise_tolerance");
            return (Criteria) this;
        }

        public Criteria andNoise_toleranceLessThan(Integer value) {
            addCriterion("noise_tolerance <", value, "noise_tolerance");
            return (Criteria) this;
        }

        public Criteria andNoise_toleranceLessThanOrEqualTo(Integer value) {
            addCriterion("noise_tolerance <=", value, "noise_tolerance");
            return (Criteria) this;
        }

        public Criteria andNoise_toleranceIn(List<Integer> values) {
            addCriterion("noise_tolerance in", values, "noise_tolerance");
            return (Criteria) this;
        }

        public Criteria andNoise_toleranceNotIn(List<Integer> values) {
            addCriterion("noise_tolerance not in", values, "noise_tolerance");
            return (Criteria) this;
        }

        public Criteria andNoise_toleranceBetween(Integer value1, Integer value2) {
            addCriterion("noise_tolerance between", value1, value2, "noise_tolerance");
            return (Criteria) this;
        }

        public Criteria andNoise_toleranceNotBetween(Integer value1, Integer value2) {
            addCriterion("noise_tolerance not between", value1, value2, "noise_tolerance");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andLast_modifyIsNull() {
            addCriterion("last_modify is null");
            return (Criteria) this;
        }

        public Criteria andLast_modifyIsNotNull() {
            addCriterion("last_modify is not null");
            return (Criteria) this;
        }

        public Criteria andLast_modifyEqualTo(Date value) {
            addCriterion("last_modify =", value, "last_modify");
            return (Criteria) this;
        }

        public Criteria andLast_modifyNotEqualTo(Date value) {
            addCriterion("last_modify <>", value, "last_modify");
            return (Criteria) this;
        }

        public Criteria andLast_modifyGreaterThan(Date value) {
            addCriterion("last_modify >", value, "last_modify");
            return (Criteria) this;
        }

        public Criteria andLast_modifyGreaterThanOrEqualTo(Date value) {
            addCriterion("last_modify >=", value, "last_modify");
            return (Criteria) this;
        }

        public Criteria andLast_modifyLessThan(Date value) {
            addCriterion("last_modify <", value, "last_modify");
            return (Criteria) this;
        }

        public Criteria andLast_modifyLessThanOrEqualTo(Date value) {
            addCriterion("last_modify <=", value, "last_modify");
            return (Criteria) this;
        }

        public Criteria andLast_modifyIn(List<Date> values) {
            addCriterion("last_modify in", values, "last_modify");
            return (Criteria) this;
        }

        public Criteria andLast_modifyNotIn(List<Date> values) {
            addCriterion("last_modify not in", values, "last_modify");
            return (Criteria) this;
        }

        public Criteria andLast_modifyBetween(Date value1, Date value2) {
            addCriterion("last_modify between", value1, value2, "last_modify");
            return (Criteria) this;
        }

        public Criteria andLast_modifyNotBetween(Date value1, Date value2) {
            addCriterion("last_modify not between", value1, value2, "last_modify");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users_pref
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 21 06:11:41 CDT 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users_pref
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}