package com.room.backend.data.mapper;

import com.room.backend.data.entity.ApartmentsInfo;
import com.room.backend.data.entity.ApartmentsInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApartmentsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    long countByExample(ApartmentsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int deleteByExample(ApartmentsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int insert(ApartmentsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int insertSelective(ApartmentsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    List<ApartmentsInfo> selectByExample(ApartmentsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    ApartmentsInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int updateByExampleSelective(@Param("row") ApartmentsInfo row, @Param("example") ApartmentsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int updateByExample(@Param("row") ApartmentsInfo row, @Param("example") ApartmentsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int updateByPrimaryKeySelective(ApartmentsInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apartments_info
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int updateByPrimaryKey(ApartmentsInfo row);
}