package com.room.backend.data.mapper;

import com.room.backend.data.entity.UsersLogin;
import com.room.backend.data.entity.UsersLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_login
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    long countByExample(UsersLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_login
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int deleteByExample(UsersLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_login
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_login
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int insert(UsersLogin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_login
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int insertSelective(UsersLogin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_login
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    List<UsersLogin> selectByExample(UsersLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_login
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    UsersLogin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_login
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int updateByExampleSelective(@Param("row") UsersLogin row, @Param("example") UsersLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_login
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int updateByExample(@Param("row") UsersLogin row, @Param("example") UsersLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_login
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int updateByPrimaryKeySelective(UsersLogin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_login
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    int updateByPrimaryKey(UsersLogin row);
}