package com.room.backend.data.entity;

import java.io.Serializable;

public class UserFavHobby implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fav_hobby.u_id
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private Integer u_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_fav_hobby.h_id
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private Integer h_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_fav_hobby
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fav_hobby.u_id
     *
     * @return the value of user_fav_hobby.u_id
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public Integer getU_id() {
        return u_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fav_hobby.u_id
     *
     * @param u_id the value for user_fav_hobby.u_id
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setU_id(Integer u_id) {
        this.u_id = u_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_fav_hobby.h_id
     *
     * @return the value of user_fav_hobby.h_id
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public Integer getH_id() {
        return h_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_fav_hobby.h_id
     *
     * @param h_id the value for user_fav_hobby.h_id
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    public void setH_id(Integer h_id) {
        this.h_id = h_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_hobby
     *
     * @mbg.generated Tue Aug 30 00:49:17 CDT 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", u_id=").append(u_id);
        sb.append(", h_id=").append(h_id);
        sb.append("]");
        return sb.toString();
    }
}