package com.room.backend.data._generated.mapper;

import com.room.backend.data._generated.entity.UserFavApartment;
import com.room.backend.data._generated.entity.UserFavApartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFavApartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_apartment
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    long countByExample(UserFavApartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_apartment
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int deleteByExample(UserFavApartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_apartment
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int insert(UserFavApartment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_apartment
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int insertSelective(UserFavApartment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_apartment
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    List<UserFavApartment> selectByExample(UserFavApartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_apartment
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int updateByExampleSelective(@Param("row") UserFavApartment row, @Param("example") UserFavApartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_apartment
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int updateByExample(@Param("row") UserFavApartment row, @Param("example") UserFavApartmentExample example);
}