package com.room.backend.data._generated.mapper;

import com.room.backend.data._generated.entity.UserFavHobby;
import com.room.backend.data._generated.entity.UserFavHobbyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFavHobbyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_hobby
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    long countByExample(UserFavHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_hobby
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int deleteByExample(UserFavHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_hobby
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int insert(UserFavHobby row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_hobby
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int insertSelective(UserFavHobby row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_hobby
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    List<UserFavHobby> selectByExample(UserFavHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_hobby
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int updateByExampleSelective(@Param("row") UserFavHobby row, @Param("example") UserFavHobbyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_fav_hobby
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int updateByExample(@Param("row") UserFavHobby row, @Param("example") UserFavHobbyExample example);
}