package com.room.backend.data._generated.mapper;

import com.room.backend.data._generated.entity.UsersInfo;
import com.room.backend.data._generated.entity.UsersInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_info
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    long countByExample(UsersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_info
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int deleteByExample(UsersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_info
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_info
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int insert(UsersInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_info
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int insertSelective(UsersInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_info
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    List<UsersInfo> selectByExample(UsersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_info
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    UsersInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_info
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int updateByExampleSelective(@Param("row") UsersInfo row, @Param("example") UsersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_info
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int updateByExample(@Param("row") UsersInfo row, @Param("example") UsersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_info
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int updateByPrimaryKeySelective(UsersInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_info
     *
     * @mbg.generated Tue Mar 21 06:11:41 CDT 2023
     */
    int updateByPrimaryKey(UsersInfo row);
}